const ADD_LOCATION = 'ADD_LOCATION';
const REMOVE_LOCATION = 'REMOVE_LOCATION';
const ADD_MULTIPLE_LOCATIONS = 'ADD_MULTIPLE_LOCATIONS';

export default { ADD_LOCATION, ADD_MULTIPLE_LOCATIONS, REMOVE_LOCATION };
