const ADD_LOCATION = 'ADD_LOCATION';
const ADD_MULTIPLE_LOCATIONS = 'ADD_MULTIPLE_LOCATIONS';
const REMOVE_LOCATION = 'REMOVE_LOCATION';
const REPLACE_LOCATIONS = 'REPLACE_LOCATIONS';

export default { ADD_LOCATION, ADD_MULTIPLE_LOCATIONS, REMOVE_LOCATION, REPLACE_LOCATIONS };
